[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
    -I ../../shared
    -I ../shared
    -D BOARD_ESP32
    -D SIM_MODE
monitor_speed = 115200
lib_deps =
    links2004/WebSockets@^2.4.1
    bblanchon/ArduinoJson@^7.0.0
