[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    -I ../../shared
    -I ../shared
    -D BOARD_MEGA
    -D BENCH_MODE
monitor_speed = 115200
lib_deps =
    arduino-libraries/Servo@^1.2.1

[env:mega_sim]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    -I ../../shared
    -I ../shared
    -D BOARD_MEGA
    -D BENCH_MODE
    -D SIM_MODE
monitor_speed = 115200
lib_deps =
    arduino-libraries/Servo@^1.2.1
